# Generated by Django 3.2.6 on 2021-08-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=1)),
                ('percent', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
