# Generated by Django 3.2.6 on 2021-08-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='color',
        ),
        migrations.RemoveField(
            model_name='title',
            name='percent',
        ),
    ]
